# Generated by Django 4.2.13 on 2024-06-11 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(verbose_name='created date')),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('max_gamer_amount', models.IntegerField()),
                ('game_date', models.DateTimeField(verbose_name='game date')),
                ('description', models.CharField(max_length=1024)),
                ('pub_date', models.DateTimeField(verbose_name='published date')),
                ('update_date', models.DateTimeField(verbose_name='update date')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.user')),
            ],
        ),
    ]
