# Generated by Django 4.2.13 on 2024-06-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_contest_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='current_gamer_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
