# Generated by Django 4.2.13 on 2024-06-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_contest_current_gamer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='current_gamer',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
