# Generated by Django 4.2.13 on 2024-06-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_user_email_user_gender_user_liked_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_sport',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
