# Generated by Django 4.2.13 on 2024-06-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
    ]
