# Generated by Django 4.2.13 on 2024-06-25 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_contest_sport_delete_user_contest_sport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='max_pacticipants',
            new_name='max_participants',
        ),
    ]
