# Generated by Django 4.2.13 on 2024-06-27 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport', '0002_auto_20240627_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contest',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participanted_contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
