# Generated by Django 4.2.13 on 2024-06-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0003_alter_contest_creator_alter_contest_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_contest',
            field=models.ManyToManyField(blank=True, to='sport.contest'),
        ),
    ]
