# Generated by Django 4.2.13 on 2024-06-26 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sport', '0004_alter_contest_created_at_alter_contest_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participanted_contests', to=settings.AUTH_USER_MODEL),
        ),
    ]
